# Generated by Django 4.0.3 on 2022-03-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnnApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='imagepostgre',
        ),
    ]
